---
title: "Statistical Rethinking \\ Chapter 4"
date: "`r format(Sys.time(), '%d %B, %Y')`"
author: Jeff Shen
output:
  pdf_document: default
---

## Linear Regression

```{r, echo=FALSE}
library(rethinking)
library(tidyverse)
data("Howell1")
d <- Howell1
precis(d)
```

```{r}
d2 <- d[d$age >= 18, ]
precis(d2)
```

```{r}
ggplot(d2, aes(x=height)) +
    geom_histogram()
```

```{r}
curve(dnorm(x, 178, 20), from=100, to=250)
curve(dunif(x, 0, 50), from=-10, to=60)
```

```{r}
prior_mu <- rnorm(1e4, 178, 20)
prior_sigma <- runif(1e4, 0, 25)
prior_h <- rnorm(1e4, mean=prior_mu, sd=prior_sigma)
dens(prior_h)
```
## Modelling 

```{r}
flist <- alist(
    height ~ dnorm(mu, sigma),
    mu ~ dnorm(178, 20),
    sigma ~ dunif(0, 25)
)

m41 <- quap(flist, data = d2)

precis(m41)
```

```{r}
par(mfrow=c(1, 2))
samps <- extract.samples(m41, 1e4)
dens(samps$mu)
dens(samps$sigma)
```
```{r}
vcov(m41)
diag(vcov(m41))
cov2cor(vcov(m41))
```

```{r}
plot(d2$height ~ d2$weight)
```

```{r}
a <- rnorm(1e2, 178, 20)
b0 <- rnorm(1e2, 0, 2)
b1 <- rlnorm(1e2, 0, 1)
b2 <- rbeta(1e2, 1, 5)
par(mfrow=c(1, 3))
dens(b0)
dens(b1)
dens(b2)
```

```{r}
plot(NULL, xlim=range(d2$weight), ylim=c(-100, 400), xlab='weight', ylab='height')
abline(h=0)
abline(h=272)
xbar <- mean(d2$weight)
for (i in 1:1e2) {
    curve(a[i] + b1[i] * (x - xbar), from=min(d2$weight), to=max(d2$weight), add = TRUE, col=col.alpha("black", 0.2))
}
```

```{r}
xbar <- mean(d2$weight)

m43 <- quap(
    alist(
        height ~ dnorm(mu, sigma), 
        mu <- a + b * (weight - xbar),
        a ~ dnorm(178, 20),
        b ~ dunif(0, 1),
        sigma ~ dlnorm(0, 3)
    ), data=d2, start=list(a=178, b=0.5, sigma=3)
)

precis(m43)
m43 %>% vcov %>% cov2cor %>% round(3)
```

```{r}
plot(d2$height ~ d2$weight)
post <- extract.samples(m43, n=1e4)
curve(mean(post$a) + mean(post$b) * (x - xbar), add=TRUE, col="red")
```
## Regression Uncertainties

```{r}
plot(d2$height ~ d2$weight)
for (i in 1:length(post)) {
    curve(post[i, ]$a + post[i, ]$b * (x - xbar), add=TRUE)
}
```

```{r}

par(mfrow=c(2, 2))

for (j in 1:4) {
    N <- 50 * j
    #dN <- slice_sample(d2, n = N, replace=FALSE)
    dN <- d2[1:N, ]
    mN <- quap(
        alist(
            height ~ dnorm(mu, sigma), 
            mu <- a + b * (weight - mean(weight)),
            a ~ dnorm(178, 20),
            b ~ dunif(0, 1),
            sigma ~ dunif(0, 50)
        ), 
        data=dN
    )
    
    nlines <- 25
    post <- extract.samples(mN, n=nlines)
    plot(dN$height ~ dN$weight, xlim=range(d2$weight), ylim=range(d2$height), xlab="weight", ylab="height")
    
    for (i in 1:nlines) {
        curve(post[i,]$a + post[i,]$b * (x - mean(dN$weight)), col=col.alpha('black', 0.2), add = TRUE)
    }
}

```

```{r}
post <- extract.samples(m43)
mu.50 <- post$a + post$b * (50 - xbar)
dens(mu.50)
PI(mu.50)
```

```{r}
weight.seq <- seq(from=25, to=70, by=0.5)
mu <- link(m43, data = data.frame(weight=weight.seq), n = 100)
```

```{r}
plot(d2$height ~ d2$weight, type='n')
for (i in 1:length(mu[,1])) {
  points(weight.seq, mu[i,], pch=16, col=col.alpha('blue', 0.05))
}
```

```{r}
mu.mean <- apply(mu, 2, mean)
mu.PI <- apply(mu, 2, PI, prob=0.89)

plot(height ~ weight, data=d2, col=col.alpha(rangi2, 0.5))
lines(weight.seq, mu.mean)
shade(mu.PI, weight.seq)
```

```{r}
sim.height <- sim(m43, data=list(weight=weight.seq))
height.PI <- apply(sim.height, 2, PI, prob=0.89)

plot(height ~ weight, d2, col=col.alpha(rangi2, 0.5))
lines(weight.seq, mu.mean)
shade(mu.PI, weight.seq)
shade(height.PI, weight.seq)
```

```{r}
precis(m43)
```
## Polynomial Regression

```{r}
d <- Howell1

d$weight_s <- (d$weight - mean(d$weight)) / sd(d$weight)
d$weight_s2 <- d$weight_s^2
d$weight_s3 <- d$weight_s^3

plot(height ~ weight_s, data=d)
```

```{r}
par(mfrow=c(1, 2))
dens(rlnorm(1e4, 2, 1), xlim=c(0, 50))
dens(runif(1e4, 0, 50), xlim=c(0, 50))
```

```{r}
m46 <- quap(
  alist(
    height ~ dnorm(mu, sigma),
    mu <- a + b1*weight_s + b2*weight_s2 + b3*weight_s3,
    a ~ dnorm(178, 20),
    b1 ~ dlnorm(0, 1),
    b2 ~ dnorm(0, 10),
    b3 ~ dnorm(0, 10),
    sigma ~ dunif(0, 20)
  ), data=d
)

precis(m46)
```


```{r}
weight.seq <- seq(from=min(d$weight_s), to=max(d$weight_s), length.out = 50)
pred_params <- list(weight_s=weight.seq, weight_s2=weight.seq^2, weight_s3=weight.seq^3)
mu <- link(m46, data=pred_params)
mu.mean <- apply(mu, 2, mean)
mu.PI <- apply(mu, 2, PI, prob=0.89)
sim.height <- sim(m46, data=pred_params)
height.PI <- apply(sim.height, 2, PI, prob=0.89)
```

```{r}
plot(height ~ weight_s, data=d, col=col.alpha(rangi2, 0.5))
lines(weight.seq, mu.mean)
shade(mu.PI, weight.seq)
shade(height.PI, weight.seq)
```

```{r}
plot(height ~ weight_s, data=d, col=col.alpha(rangi2, 0.5))
for (i in 1:50) {
  lines(weight.seq, mu[i,], col=col.alpha('black', 0.1))
}
```

## Splines

```{r, echo=FALSE}
data("cherry_blossoms")
d <- cherry_blossoms
```

```{r}
precis(d)
```


```{r}
d2 <- d[complete.cases(d$doy),]
n_knots <- 15
knot_list <- quantile(d2$year, probs=seq(0, 1, length.out = n_knots))
knot_list
```

```{r}
library(splines)
B <- bs(d2$year, knots=knot_list[-c(1, n_knots)], degree=3, intercept = TRUE)
```

```{r}
m47 <- quap(
  alist(
    D ~ dnorm(mu, sigma),
    mu <- a + B %*% w,
    a ~ dnorm(100, 10),
    w ~ dnorm(0, 10),
    sigma ~ dexp(1)
  ), data=list(D=d2$doy, B=B),
  start=list(w=rep(0, ncol(B)))
)
```

```{r}
post <- extract.samples(m47)
w <- apply(post$w, 2, mean)
plot(NULL, xlim=range(d2$year), ylim=c(-6, 6), xlab='year', ylab='basis * weight')
for (i in 1:ncol(B)) {
  lines(d2$year, w[i] * B[,i])
}
```

```{r}
mu <- link(m47)
mu.mean <- apply(mu, 2, mean)
mu.PI <- apply(mu, 2, PI, 0.89)
sim.doy <- sim(m47, d2)
doy.PI <- apply(sim.doy, 2, PI, prob=0.89)
```

```{r}
plot(d2$year, d2$doy, col=col.alpha(rangi2, 0.3))
lines(d2$year, rep(mean(d2$doy), length(d2$year)), lty='dotted')
lines(d2$year, mu.mean)
shade(mu.PI, d2$year, col=col.alpha('black', 0.5))
shade(doy.PI, d2$year, col=col.alpha('black', 0.3))
```

